config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root to: "boards#index"
  resources :reminders


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  #------------------------------------------------------- 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  # get '/sidekiq' => redirect('/')
  #------------------------------------------------------- 


  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end

end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :board
    has_many :todos , dependent: :destroy
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController    
    before_action :authenticate_user!
    load_and_authorize_resource
    
    def index
        @lists = @lists.where(:board_id => params[:board_id])
        @board_id = params[:board_id]
        @title  = @lists.length > 0 ? @lists.first.board.name : "EMPTY BOARD"
    end

    def new
        @board_id = params[:format]
    end

    def create
        # load_and_authorize will defaulty look for its list_params
        # @list.user_id = current_user.id will also create user with id 
        #  so we dont have to 
        # @list = List.new(list_params)
        if @list.save
            redirect_to(lists_path(:board_id =>@list.board_id))
        else
            render('new')
        end
    end

    def edit
        # @list = List.find_by_id(params[:id])
    end

    def update
        # @task = List.find_by_id(params[:id])
        if @list.update(list_params)
            redirect_to(lists_path(:board_id => @list.board_id))
        else
            render('edit')
        end
    end
    
    def destroy
        # @task = List.find(params[:id])
        @list.destroy
        flash[:notice] = "Task-List Deleted"
        redirect_to(lists_path(:board_id => @list.board_id))
    end

    private

    def list_params
        params.require(:list).permit(:name ,:board_id)
    end
end

app/views/lists/edit.html.erb
<h>Update name List</h>
<%= form_for(@list) do |f| %>
    <%= f.text_field(:name) %>
    <%= f.submit %>
<%end%>

app/views/lists/index.html.erb
<div>
    <a herf= <%= boards_path %> class= 'bg-gray-100'>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12.066 11.2a1 1 0 000 1.6l5.334 4A1 1 0 0019 16V8a1 1 0 00-1.6-.8l-5.333 4zM4.066 11.2a1 1 0 000 1.6l5.334 4A1 1 0 0011 16V8a1 1 0 00-1.6-.8l-5.334 4z" />
        </svg>
    </a>
</div>
<%# link_to '<<Back' , boards_path%>

<div class = 'grid bg-red-300 content-center' >
    <div>
        <%= @title %>
    </div>
</div>

<table>

<tr>
    <% @lists.each do |list| %>
        <th>

            <div class="dropdown">

                <a class = "dropdown-item" href= <%= todos_path(:list_id => list.id)%> > 
                    <div class= 'text-3xl hover:text-base italic'> 
                        <%= list.name %>
                    </div>
                </a>
                
                <% unless current_user.has_role?(:viewer ,Board.find(list.board.id))%>
                    <a class = "dropdown-item" href= <%= edit_list_path(list)%> >
                        Edit List
                    </a>
                    <div data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= button_to "Delete List" , list_path(list) , method: :delete ,class: "bg-blue-500 hover:bg-blue-700 text-white font-bold rounded px-2 py-1" %>
                    </div>
        
                    <a class = "dropdown-item" href= <%= new_todo_path(:id=> list.id ,:board_id =>@board_id)%> >
                        Add Todo
                    </a>
                <% end %>

            </div>

        </th>

    <%end%>

    <% unless current_user.has_role?(:viewer, Board.find(@board_id)) %>
        <th>
            <td> <%= link_to "Create-List" , new_list_path(@board_id) ,class:"bg-blue-500 hover:bg-blue-700 text-white font-bold rounded px-2 py-1" %> </td>
        </th>
    <%end%>

</tr>

</table>

app/views/lists/new.html.erb
<div class= "text-lg font-bold">
    Create new List
</div>

<%= form_for(@list) do |f| %>
    <div class= 'flex'>
        <div class = 'field'>
            <%= f.text_field :name ,autofocus: true , class: "rounded bg-white shadow-md py-2 px-3" %>
        </div>
        <%= f.hidden_field(:board_id , :value => @board_id) %>
        <div class='field px-2'>
            <%= f.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold rounded px-3 py-2" %>
        </div>
    </div>
<%end%>