config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root to: "boards#index"
  resources :reminders


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  #------------------------------------------------------- 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  # get '/sidekiq' => redirect('/')
  #------------------------------------------------------- 


  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end

end

app/views/shared/_navbar.html.erb
<nav class= "bg-gray-200">
    <div class = "max-w-7xl h-10 mx-auto">
      <div class= "flex justify-between py-1.5">
        <div class = "flex justify-between space-x-4">
          <div>
            <a herf ='#' class = 'flex'>
              <svg class = 'h-6 w-6 mr-1 text-blue-500' xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
              </svg>
              <span>Trello Clone</span>    
            </a>
          </div>
        </div>

        <div>
          <% if user_signed_in? %>
            <% if @notifications_num != nil %>
      
                <a href=<%= reminders_path %>>
                      Notifications 
                    <span> <%= @notifications_num %> </span>
                </a>
                
            <% end %>
              <%= link_to 'Logout' , destroy_user_session_path ,method: :delete %>
          <% else %>
              <div>
                <%= link_to 'Register' ,new_user_registration_path %>
                <%= link_to 'Sign in' , new_user_session_path %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
</nav>