config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root to: "boards#index"
  resources :reminders


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  #------------------------------------------------------- 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  # get '/sidekiq' => redirect('/')
  #------------------------------------------------------- 


  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% name = current_user.username %>
<h1>Welcome <%= name%> </h1>

<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 140px;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <svg class="bi me-2" width="16" height="16"><use xlink:href="#bootstrap"></use></svg>
    <span class="fs-4",style="display: inline-block">Boards </span>
  </a>

  <hr>

  <div class="Board">
    <% @boards.each do |board| %>
      <table class="table">
        <tr> <%= board.name %> <tr>
        <br>
        <tr> <%= link_to("Show lists" , home_path(board)) %><tr>
        <br>
        <tr> <%= button_to "Delete" ,board_path(board),  data: { confirm: 'Are you sure you want to delete this alert?' } ,method: :delete %> </tr>
      </table>
        <hr>
    <%end%>
  </div>
    
  <div>
    <%= link_to('New Board' ,new_board_path , class: 'action new')%>
  </div>
  
  <hr>
</div>