config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root to: "boards#index"
  resources :reminders


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  #------------------------------------------------------- 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  # get '/sidekiq' => redirect('/')
  #------------------------------------------------------- 


  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end

end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :list
    
    enum status: {
        Pending: 0,
        Done: 1,
        Working: 2 
    }, _prefix: true
    
    def one_day_diff?
        date = due_date.to_date
        curr_date = Time.zone.today
        if curr_date.month == date.month && curr_date.year == date.year
            # puts date.day , curr_date.day
            if (date.day - curr_date.day).abs <= 1 and curr_date.day <= date.day
                return true
            end
        end
        return false
    end
end 

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @todos = @todos.where(:list_id => params[:list_id])
  end

  def new
    # @todo = Todo.new
    @task_id = params[:id]
    @board_id = params[:board_id]
  end 

  def create
    @todo = Todo.new(todo_params)
    @board_id = params[:todo][:board_id]
    if @todo.save
      ReminderAlertJob.set(wait_until: @todo.due_date).perform_later(@todo)
      redirect_to(lists_path(:board_id => @board_id))
    else
      render('new')
    end
  end

  def show
    @todo = Todo.find_by_id(params[:id])
  end

  def edit
    @todo  = Todo.find_by_id(params[:id])
  end
  
  def update
    @todo  = Todo.find_by_id(params[:id])
    
    if @todo.update(todo_params)
      redirect_to(todo_path(@todo.id))
    else
        render('edit')
    end
  end

  def destroy
    @todo = Todo.find_by_id(params[:id])
    @list_id = @todo.list.id
    @todo.destroy
    flash[:notice] = "Todo Deleted"
    redirect_to(todos_path(:list_id => @list_id))
  end 

  private

  def todo_params
    params.require(:todo).permit(:list_id ,:title ,:description ,:due_date ,:status)
  end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= f.text_field(:title,placeholder: 'Title') %>
<%= f.text_field(:description,placeholder: 'Description') %>
<%= f.select :status, ["Pending","Done","Working"] %>
<%= f.date_field(:due_date) %>

app/views/todos/edit.html.erb
<h1>Update Todo</h1>
<%= form_for(@todo) do |f|%>
    <%= render(:partial=>'form', :locals =>{:f=>f})%>
    <%= f.submit() %>
<%end%>

app/views/todos/index.html.erb
<% if @todos.length != 0 %>
    <%= link_to '<<Back' , lists_path(:board_id => @todos.first.list.board_id)%>
<% end %>
<div class = 'bg-red-300 font-bold'>
    <%= @todos.length>0 ? @todos[0].list.name : "Empty ToDo " %> 
</div>
<div class = 'grid grid-cols-2 gap-4'>
    <% @todos.each do|todo| %>
    <div class = 'bg-gray-300 px-2'>
        <div class = 'flex justify-around'>
            <div class = 'flex py-2'>
                <div class = 'text-md font-bold'>
                    Title:
                </div>
            
                <div class ="px-2 text-blue-700 rounded border-4 border-indigo-500/100" >
                    <%= link_to todo.title ,todo_path(todo.id) %>    
                </div>
            </div>

            <div class = "text-red-900">
                Due Date:
                <%= todo.due_date.strftime("%d-%m-%Y") %>
            </div>
            
            <div class= "text-blue-900">
                Status :  <%= todo.status %>
            </div>

        </div>

        <div class = "text-md font-bold">
            Description:
        </div>
        
        <p>
            <%= todo.description %>
        </p>
    </div>
    <%end%>
</div>

app/views/todos/new.html.erb
<h1>Create new Todo</h1>
<%= form_for(@todo) do |f|%>
    <%= render(:partial =>'form', :locals => {:f=>f})%>
    <%= f.hidden_field(:board_id , :value => @board_id) %>
    <%= f.hidden_field(:list_id, :value => @task_id)  %>
    <%= f.submit() %>   
<%end%>

app/views/todos/show.html.erb
<%= link_to '<<Back' , todos_path(:list_id => @todo.list_id)%>

<h1>ToDo-Information</h1>
<br>
<h2>Title</h2>
<%= @todo.title %>
<br>

<h2>Due Date</h2>
<%= @todo.due_date.strftime("%d-%m-%Y") %>
<br>

<h2>Description</h2>
<%= @todo.description %>

<h5>Status :  <%= @todo.status %></h5>

<br>
<% unless current_user.has_role?(:viewer ,Board.find(@todo.list.board.id))%>
    <%= link_to("Edit/Update" ,edit_todo_path(@todo.id),  :class => 'action edit bg-blue-500 hover:bg-blue-700 text-white font-bold rounded' ) %>
    <%= button_to "Delete" ,todo_path(@todo.id), method: :delete , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold rounded p-2" %>
<%end%>